markdown: redcarpet
name: Agile Delivery Services Blanket Purchase Agreement
exclude:
- go
- copy-template
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md

permalink: pretty

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction and updates
  url: index.html
  internal: true
- text: Information for agency partners
  url: buyers/
  internal: true
- text: Information for vendors
  url: vendors/
  internal: true
- text: Contact 18F
  url: contact-18f/
  internal: true

repos:
- name: Agile Delivery Services BPA Guide
  description: Main repository

page_gen:
  - data: orders
    template: badges
    name: title
    dir: badges
    extension: svg

google_analytics_ua: UA-48605964-19

# Data Source
data_dir: data
