baseurl: /ads-bpa
markdown: redcarpet
name: Agile Delivery Services Blanket Purchase Agreement
exclude:
- go
- copy-template
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md

permalink: pretty

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Information for vendors
  url: index.html
  internal: true
- text: Information for buyers
  url: buyers/
  internal: true
- text: How can agencies use the Agile BPA
  url: how-can-i-use-the-agile-bpa/
  internal: true
- text: Submit a Project for the Agile BPA
  url: https://docs.google.com/a/gsa.gov/forms/d/1w0eSRMWwgwsi-7OYmBAVkOmQnhzXbQRU6JGXUd6Xrps/viewform
  internal: false
- text: Contact 18F
  url: contact-18f/
  internal: true

repos:
- name: Agile Delivery Services BPA Guide
  description: Main repository
  url: https://github.com/18F/ads-bpa

# Style Variables
brand_color: "#1188ff"

google_analytics_ua: UA-48605964-19
