markdown: redcarpet
name: Agile Blanket Purchase Agreement
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

theme: guides_style_18f

permalink: pretty
highlighter: rouge
incremental: true

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# To expand all navigation bar entries by default, set this property to true:
expand_nav: true

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Overview
  internal: true
- text: Working with us
  url: working-with-us/
  internal: true
  children:
  - text: For agency partners
    url: agency-partners/
    internal: true
  - text: For industry partners
    url: industry-partners/
    internal: true
  - text: Post-award teams
    url: our-project-team/
    internal: true
- text: Orders
  url: orders/
  internal: true
- text: Ordering guide
  url: ordering-guide/
  internal: true
- text: Awardees
  url: pool-three-awardees/
  internal: true
- text: Contact Us
  url: contact-us/
  internal: true

# Data Source
data_dir: data

scripts: assets/css/styles.scss

repos:
- name: Agile BPA Solicitation Documents
  description: All the agile bpa soliciation
  url: https://github.com/18F/ads-bpa

back_link:
  url: https://18f.gsa.gov/tags/acquisition-services/
  text: Read 18F acquisition blog posts

google_analytics_ua: UA-48605964-19

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
- scope:
    path: ""
  values:
    layout: default

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
